### PR TITLE
Check for empty string robot names

### PR DESCRIPTION
**Pull request by enilsen16**
I have been looking into using Hedwig (see [example](https://github.com/enilsen16/Eva)) for a messenger bot and didn't want to have to prefix messages with a robots name. It seems that an empty string is a valid name (hopefully by design). Anyway i think it might make sense to add a note to the readme about this. If not the readme then maybe the generator itself?

### CODE REVIEW

**Comment by scrogson** [comment]
Hey there @enilsen16!

I think that is a bug and not by design. If you don't want to mention the bot's name for a responder to match, you should use the `hear` macro. `respond` is for matching when the bot is mentioned.

Maybe the docs could be more clear about `hear` vs. `respond`?

**Comment by enilsen16** [comment]
oh interesting, after looking closer at the example responders that makes sense. Let me go ahead and add a check in the generator then.

**Comment by enilsen16** [comment]
Hey @scrogson, 

I went ahead and added some checks in the generator and in the supervisor to prevent the same mistake I made.

**Comment by enilsen16** [comment]
@scrogson Let me know if something is missing here... 👍

**Pull request closed without merging**
